# Site settings
title: Junkiejem | Webfolio © 2018
email: jemaiimanao@gmail.com
url: https://junkiejem.github.io
description: "After x years in programming, I came to love JavaScript. XD"
keywords: "webapps, websites, web development, HTML, CSS, PHP, JavaScript"
skills: "UX/UI Engineer - Web/Software Developer - Occasional Content Curator"
meta_author: Manao Jem

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: junkiejem

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/junkiejem
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/junkiejem
  - title: bitbucket
    url: http://bitbucket.org/junkiejem
  - title: github
    url: http://github.com/junkiejem

# Postal address (add as many lines as necessary)
address:
  - line: Block 30, Lot 6B, Cherry Blossom street
  - line: Dona Manuela Subdivision, Las Pinas City, PH

# Credits content
credits: 'Hallo! I am Joana Elizabeth Manao. You can call me "Jem" for short. I am a UI/UX engineer (slash) full-stack web developer for over 8 years now. I have already developed a quite few number of web applications, from corporate to e-commerce websites, and anything built on HTML, JS, CSS & PHP, you name it! ;) Drop a line! I will try my best to respond immediately as possible.'

# Build settings
markdown: kramdown
permalink: pretty
